version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true
  show-stats: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
  
  # Disable gosec for development tools - too many false positives
  disable:
    - gosec
    
  # Exclude common low-risk issues
  exclusions:
    rules:
      # Ignore errcheck for Close() calls - very common and usually safe
      - text: "Error return value of.*Close.*is not checked"
        linters:
          - errcheck
      
      # Ignore errcheck for os.Remove - cleanup operations 
      - text: "Error return value of.*os.Remove.*is not checked"
        linters:
          - errcheck
          
      # Ignore gosec G104 (errors unhandled) for Close() calls
      - text: "G104.*Close"
        linters:
          - gosec
      
      # Ignore gosec G104 for os.Remove - cleanup operations 
      - text: "G104.*os.Remove"
        linters:
          - gosec
          
      # Ignore gosec file permission warnings for standard permissions
      - text: "G301.*0755"
        linters:
          - gosec
      - text: "G306.*0644"
        linters:
          - gosec
          
      # Ignore gosec file inclusion warnings for legitimate file operations
      - text: "G304.*Potential file inclusion"
        linters:
          - gosec
          
      # Ignore gosec subprocess warnings for git commands (trusted)
      - text: "G204.*git"
        linters:
          - gosec
          
      # Ignore gosec subprocess warnings for docker commands (trusted)
      - text: "G204.*docker"
        linters:
          - gosec
          
      # Ignore revive export comment requirements - often not needed for internal packages
      - text: "exported.*should have comment or be unexported"
        linters:
          - revive
          
      # Ignore revive package comment requirements
      - text: "should have a package comment"
        linters:
          - revive
          
      # Ignore revive unused parameter warnings
      - text: "unused-parameter"
        linters:
          - revive
          
      # Ignore revive variable naming for ID/UUID fields (common in APIs)
      - text: "var-naming.*Id.*should be.*ID"
        linters:
          - revive
      - text: "var-naming.*Uuid.*should be.*UUID"
        linters:
          - revive
      - text: "var-naming.*Tcp.*should be.*TCP"
        linters:
          - revive
          
      # Ignore some revive style issues that are acceptable
      - text: "indent-error-flow"
        linters:
          - revive
      - text: "empty-block"
        linters:
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true

severity:
  default: error
  rules:
    - linters:
        - misspell
      severity: warning