version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true
  show-stats: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true

severity:
  default: error
  rules:
    - linters:
        - misspell
      severity: warning