version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - unconvert

  # Exclude targeted low-risk issues
  exclusions:
    rules:
      # Ignore errcheck for Close() calls - very common and usually safe
      - text: "Error return value of.*Close.*is not checked"
        linters:
          - errcheck

      # Ignore errcheck for os.Remove - cleanup operations
      - text: "Error return value of.*os.Remove.*is not checked"
        linters:
          - errcheck

      # Gosec G104: Allow ignoring errors for cleanup operations
      - text: "G104"
        linters:
          - gosec

      # Gosec G204: Allow subprocess calls, this is an RCE as a service app anyway
      - text: "G204"
        linters:
          - gosec

      # Gosec G301/G306: Allow standard directory/file permissions for all files
      - text: "G301"
        linters:
          - gosec
      - text: "G306"
        linters:
          - gosec

      # Gosec G304: Allow file operations for legitimate development tool functionality
      - text: "G304.*Potential file inclusion via variable"
        linters:
          - gosec

      # Gosec G103: Allow unsafe pointer usage for PTY operations
      - text: "G103.*Use of unsafe calls should be audited"
        linters:
          - gosec

      # Revive: Reduce noise for internal packages
      - text: "exported.*should have comment or be unexported"
        linters:
          - revive
      - text: "should have a package comment"
        linters:
          - revive
      - text: "unused-parameter"
        linters:
          - revive
      - text: "var-naming.*Id.*should be.*ID"
        linters:
          - revive
      - text: "var-naming.*Uuid.*should be.*UUID"
        linters:
          - revive
      - text: "var-naming.*Tcp.*should be.*TCP"
        linters:
          - revive
      - text: "indent-error-flow"
        linters:
          - revive
      - text: "empty-block"
        linters:
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true
