name: Publish VS Code Extension

on:
  push:
    tags:
      - 'feature_vscode_*'  # e.g., feature_vscode_1.1.0
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .devcontainer/features/feature/catnip-vscode-extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .devcontainer/features/feature/catnip-vscode-extension/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run compile

      - name: Package extension
        run: npm run package

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: catnip-sidebar-vsix
          path: .devcontainer/features/feature/catnip-sidebar.vsix
          retention-days: 30

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: .devcontainer/features/feature/catnip-sidebar.vsix
          body: |
            ## W&B Catnip VS Code Extension

            Published to VS Code Marketplace: https://marketplace.visualstudio.com/items?itemName=wandb.catnip-sidebar

            ### Installation
            - Install from VS Code Marketplace: Search for "W&B Catnip"
            - Or install from VSIX: Download the `.vsix` file and run `code --install-extension catnip-sidebar.vsix`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
