name: Test Go

on:
  push:
    paths:
      - "container/**"
      - ".github/workflows/test-go.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # TODO: windows-latest fails tests for some reason, one day maybe...
        go-version: ["1.24"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: container/go.sum

      - name: Download dependencies
        run: go mod download
        working-directory: container

      - name: Run tests
        run: go test -v ./...
        working-directory: container

      - name: Run go vet
        run: go vet ./...
        working-directory: container

      - name: Build CLI
        run: go build -o bin/catctrl ./cmd/cli/main.go
        working-directory: container

      - name: Build Server
        run: go build -o bin/catnip ./cmd/server/main.go
        working-directory: container

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: container/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          working-directory: container
          args: --verbose

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: container/go.sum

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: check
          workdir: container
